### ISSUE TITLE
Move specification of header from .cls file to .tex file

### ISSUE THREAD

**Issue by stevewillson** [glallen01/army-memorandum-class#29]
Request to move the specification of the 'DA Header' from the .cls file to the .tex file. The unit header will differ from organization to organization.

Recommend adding an ```addaddress``` command to the .cls file to allow users to specify the address in the .tex file.

**Comment by stevewillson** [comment]
I didn't realize that I could add an ```address{}``` block in the .tex file to specify the organizational address.

**Comment by glallen01** [comment]
right... see [example-grid.tex#L23](https://github.com/glallen01/army-memorandum-class/blob/master/examples/example-grid.tex#L23).

I should add documentation of this to #28.
