### ISSUE TITLE
First Item is Indented Wrong

### ISSUE THREAD

**Issue by gimmx** [glallen01/army-memorandum-class#40]
No matter which settings or LATEX I use, the first item is always indented too far to the left. Overleaf does not have this behavior, so it must be a dependency on an old include.

**Comment by glallen01** [comment]
<img width="97" alt="Screenshot 2023-10-09 at 3 08 06 PM" src="https://github.com/glallen01/army-memorandum-class/assets/796167/c806381f-1e24-4759-acc1-e2a4cd2d7886">

If it looks something like this, you probably need a blank line after `\begin{document}` in LaTeX, these blank lines are significant, as they imply `\par` and trigger new paragraph creation:

```
\begin{document}

\begin{enumerate}
```

If this doesn't help, please post a stripped down minimal example, and also which command you're using to compile it.

**Comment by gimmx** [comment]
I'm using a docker build on Windows:

compile.bat
```
@echo off

:: Define the image name
set IMAGE_NAME=latexmk-container

:: Build the Docker image
docker build -t %IMAGE_NAME% .

:: Check if a LaTeX file was provided as an argument
set tex_file=mypdf.tex
if "%~1" neq "" (
  set tex_file=%~1
)

:: Run the Docker container with the current directory mounted
docker run --rm -v %cd%:/latex %IMAGE_NAME% %tex_file%
```

Dockerfile
```
FROM texlive/texlive:latest

# Install latexmk
#RUN apt-get update && apt-get install -y latexmk
COPY arial /usr/local/share/fonts/

# Set working directory
WORKDIR /latex

# Command to run latexmk when the container starts
ENTRYPOINT ["latexmk", "-pdf", "-lualatex"]
CMD ["mypdf.tex"]
```

mypdf.text
```
\documentclass{armymemo}

\address{ARMY UNIT}
\address{123 Somewhere Drive}
\address{San Diego, CA 90210}

\author{John B. Smith}\rank{COL}\branch{CY}\title{Commanding}
\officesymbol{TEST}
\signaturedate{9 October 2023}
\memoline{MEMORANDUM FOR RECORD}
\documentmark{\textbf{CUI//OPSEC//FEDCON}}
\subject{Some Random Subject about Something Army ish}

\begin{document}

\begin{enumerate}

\item Reference: Policy 
\item Instructions:
  \begin{enumerate}
  \item Item 1
  \item Item 2
  \end{enumerate}
\item Effective immediately

\end{enumerate}
\end{document}

```
Still misaligned:

![image](https://github.com/glallen01/army-memorandum-class/assets/54279755/468b699a-0c4e-45d3-91ed-a7297934faf3)

Overleaf doesn't make this mistake.

**Comment by glallen01** [comment]
Interesting. I think it has something to do with texlive 2023 vs 2022. I recompiled other files and ran into the same issue. On overleaf, switching to lualatex and 2023 reproduced the issue, switching back to 2022 worked as expected: 
<img width="383" alt="image" src="https://github.com/glallen01/army-memorandum-class/assets/796167/dc18609f-aa9c-47d2-84c3-157ee9f35611">

Something changed somewhere in one of the packages and I'll have to dig around and figure out what to do in response. For now use Texlive 2022 (or try `texlive/texlive:TL2022-historic` for your docker)

**Comment by gimmx** [comment]
Only texlive/texlive:TL2021-historic corrects the issue. 2022 has the same indentation problem. But working for now so I'll take it, thank you!

**Comment by glallen01** [comment]
I think I've got it, try the updated class file and let me know if it works.

**Comment by gimmx** [comment]
Works perfectly now.
