### ISSUE TITLE
DoD header is offset 0.5in to the left on XeLaTeX 2021 and newer

### ISSUE THREAD

**Issue by 0xC0ncord** [glallen01/army-memorandum-class#41]
I noticed the DoD header appeared to be too far to the left on XeLaTeX 2023. I was able to verify this behavior using Overleaf and compiling the example memo. This doesn't seem to happen on XeLatex 2020 and older.

![image](https://github.com/glallen01/army-memorandum-class/assets/8011001/4e59e726-d8a0-402c-ba3e-ae0ac63f4526)

Adding an `xshift=0.5in` to the header command fixed it for me:

![image](https://github.com/glallen01/army-memorandum-class/assets/8011001/57c43d11-c473-45d7-806f-fb4329461b1b)

**Comment by glallen01** [comment]
It does seem to be working ok with lualatex. Apparently xelatex also breaks `\documentmark{}.` While I think I started this originally using xelatex for some forgotten reason, I'd use lualatex if possible from here on.

**Comment by 0xC0ncord** [comment]
> It does seem to be working ok with lualatex. Apparently xelatex also breaks `\documentmark{}.` While I think I started this originally using xelatex for some forgotten reason, I'd use lualatex if possible from here on.

I can confirm this doesn't happen in my TeX setup using luatex. I'll consider this "fixed" for me but I'm not sure if there's anything that can be done in the class to workaround this for xetex.

**Comment by glallen01** [comment]
Reading through stackexchange, I just learned about https://ctan.org/pkg/iftex, which might help with engine specific work arounds. Where did you put that `xshift=0.5in` ?

**Comment by glallen01** [comment]
> The increasing importance of tagged PDFs means that this requires a move away from XeTeX. We will continue to address issues with XeTeX support in team-maintained LaTeX code on a best-effort basis. *No new functionality will be added for XeTeX by the LaTeX team.* It is likely that over time functionality may become more restricted, and *users are urged to migrate XeTeX documents to LuaTeX.*

https://www.latex-project.org/news/latex2e-news/ltnews40.pdf
